-- Supabase SQL Editorで実行するVer.3用スキーマ。金額は円単位整数。
create table if not exists students (
 student_id bigint generated by default as identity primary key, name text not null unique,
 school_location text not null default '', grade text not null default '', monthly_fee integer not null default 0,
 recital_fee integer not null default 0, enrollment_date date, withdrawal_date date,
 enrollment_status text not null default '在籍' check (enrollment_status in ('在籍','休会','退会')),
 guardian_name text default '', phone text default '', email text default '', notes text default '',
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists charges (
 charge_id bigint generated by default as identity primary key, student_id bigint not null references students(student_id),
 target_month text not null, charge_type text not null, charge_amount integer not null check(charge_amount>=0),
 due_date date, charge_status text not null default '請求中', notes text default '',
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(student_id,target_month,charge_type)
);
create table if not exists payments (
 payment_id bigint generated by default as identity primary key, charge_id bigint not null references charges(charge_id),
 student_id bigint not null references students(student_id), student_name text not null, target_month text not null,
 payment_type text not null, charge_amount integer not null, amount_received integer not null check(amount_received>0),
 received_date date not null default current_date, received_time time not null default localtime,
 payment_method text not null, received_by text not null, stamp_confirmed boolean not null default true,
 stamp_confirmed_at timestamptz, stamp_confirmed_by text, payment_status text not null default '処理完了',
 calendar_event_id text, notes text default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 cancelled_at timestamptz, cancellation_reason text
);
create table if not exists audit_logs (
 log_id bigint generated by default as identity primary key, action_type text not null, target_table text not null,
 target_id bigint, student_id bigint, action_detail text not null, operator_name text not null,
 action_datetime timestamptz not null default now()
);
create table if not exists allowed_teachers (
 email text primary key, display_name text default '', created_at timestamptz not null default now()
);
create table if not exists calendar_mappings (
 normalized_title text primary key, student_id bigint not null references students(student_id),
 original_title text not null, created_by text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists migration_runs (
 source_sha256 text primary key, source_name text not null, imported_at timestamptz not null default now(), detail jsonb not null default '{}'::jsonb
);
create unique index if not exists payments_calendar_event_once
 on payments(calendar_event_id) where calendar_event_id is not null and cancelled_at is null;
alter table students enable row level security;
alter table charges enable row level security;
alter table payments enable row level security;
alter table audit_logs enable row level security;
alter table allowed_teachers enable row level security;
alter table calendar_mappings enable row level security;
alter table migration_runs enable row level security;
create policy "teacher reads own allow entry" on allowed_teachers for select to authenticated using (lower(email)=lower(auth.jwt()->>'email'));
create policy "allowed teachers students" on students for all to authenticated using (exists(select 1 from allowed_teachers a where lower(a.email)=lower(auth.jwt()->>'email'))) with check (exists(select 1 from allowed_teachers a where lower(a.email)=lower(auth.jwt()->>'email')));
create policy "allowed teachers charges" on charges for all to authenticated using (exists(select 1 from allowed_teachers a where lower(a.email)=lower(auth.jwt()->>'email'))) with check (exists(select 1 from allowed_teachers a where lower(a.email)=lower(auth.jwt()->>'email')));
create policy "allowed teachers payments" on payments for all to authenticated using (exists(select 1 from allowed_teachers a where lower(a.email)=lower(auth.jwt()->>'email'))) with check (exists(select 1 from allowed_teachers a where lower(a.email)=lower(auth.jwt()->>'email')));
create policy "allowed teachers audit" on audit_logs for all to authenticated using (exists(select 1 from allowed_teachers a where lower(a.email)=lower(auth.jwt()->>'email'))) with check (exists(select 1 from allowed_teachers a where lower(a.email)=lower(auth.jwt()->>'email')));
create policy "allowed teachers mappings" on calendar_mappings for all to authenticated using (exists(select 1 from allowed_teachers a where lower(a.email)=lower(auth.jwt()->>'email'))) with check (exists(select 1 from allowed_teachers a where lower(a.email)=lower(auth.jwt()->>'email')));

-- 初回のみSQL Editorで実行（実際の先生のメールへ置換）:
-- insert into allowed_teachers(email,display_name) values ('teacher@example.com','先生');

-- SQLiteからIdentity列のIDを明示して移行した後、service_roleだけが呼び出す。
create or replace function sync_migration_identity_sequences()
returns table(table_name text,column_name text,max_id bigint,sequence_value bigint,is_called boolean)
language plpgsql
security definer
set search_path = ''
as $$
declare
 v_table text; v_column text; v_sequence text; v_max bigint; v_has_rows boolean;
begin
 lock table public.students,public.charges,public.payments,public.audit_logs in access exclusive mode;
 for v_table,v_column in
  select * from (values
   ('public.students','student_id'),('public.charges','charge_id'),
   ('public.payments','payment_id'),('public.audit_logs','log_id')
  ) as identity_columns(table_name,column_name)
 loop
  v_sequence:=pg_catalog.pg_get_serial_sequence(v_table,v_column);
  if v_sequence is null then raise exception 'Identity sequence not found for %.%',v_table,v_column; end if;
  execute pg_catalog.format('select max(%I),count(*)>0 from %s',v_column,v_table::regclass)
   into v_max,v_has_rows;
  perform pg_catalog.setval(v_sequence::regclass,coalesce(v_max,1),v_has_rows);
  table_name:=pg_catalog.split_part(v_table,'.',2); column_name:=v_column;
  max_id:=v_max; sequence_value:=coalesce(v_max,1); is_called:=v_has_rows;
  return next;
 end loop;
end $$;
revoke all on function sync_migration_identity_sequences() from public;
grant execute on function sync_migration_identity_sequences() to service_role;

create or replace function complete_lesson_payment(
 p_charge_id bigint,p_payment_method text,p_received_by text,p_calendar_event_id text default null
) returns bigint language plpgsql security invoker as $$
declare c charges%rowtype; paid integer; remaining integer; new_id bigint;
begin
 select * into c from charges where charge_id=p_charge_id for update;
 if not found or c.charge_status in ('入金済','免除','取消') then raise exception 'この請求は登録できません'; end if;
 select coalesce(sum(amount_received),0) into paid from payments where charge_id=p_charge_id and cancelled_at is null;
 remaining:=c.charge_amount-paid;
 if remaining<=0 then raise exception 'この請求はすでに受領済みです'; end if;
 insert into payments(charge_id,student_id,student_name,target_month,payment_type,charge_amount,amount_received,
  payment_method,received_by,stamp_confirmed,stamp_confirmed_at,stamp_confirmed_by,payment_status,calendar_event_id)
 select c.charge_id,c.student_id,s.name,c.target_month,c.charge_type,c.charge_amount,remaining,
  p_payment_method,p_received_by,true,now(),p_received_by,'処理完了',p_calendar_event_id from students s where s.student_id=c.student_id
 returning payment_id into new_id;
 update charges set charge_status='入金済',updated_at=now() where charge_id=c.charge_id;
 insert into audit_logs(action_type,target_table,target_id,student_id,action_detail,operator_name)
 values('受領・押印済み','payments',new_id,c.student_id,c.target_month||' '||c.charge_type||' '||remaining||'円',p_received_by);
 return new_id;
end $$;
